apiVersion: apps/v1
kind: Deployment
metadata:
  name: tourguard-backend
  labels:
    app: tourguard-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tourguard-backend
  template:
    metadata:
      labels:
        app: tourguard-backend
    spec:
      containers:
        - name: tourguard-backend
          image: your-registry/tourguard-backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: tourguard-secrets
                  key: database-url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: tourguard-secrets
                  key: jwt-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: tourguard-backend
spec:
  selector:
    app: tourguard-backend
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
