name: TourGuard CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install backend dependencies
        run: |
          pwd
          ls -l backend/
          cd backend && npm install

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: "stable"

      - name: Install Flutter dependencies
        run: cd mobile && flutter pub get

      - name: Run backend tests
        run: |
          pwd
          ls -l backend/
          cd backend && npm test

      - name: Run Flutter tests
        run: |
          cd mobile
          flutter test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: zafus/tourguard-backend:latest

      - name: Build Flutter app
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: "stable"

      - name: Build Android app
        run: |
          cd mobile
          flutter build appbundle

  deploy:
    # needs: build
    # if: github.ref == 'refs/heads/main'
    # runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/checkout@v2

    #   - name: Install kubectl
    #     uses: azure/setup-kubectl@v1

    #   - name: Set up kubeconfig
    #     run: |
    #       echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
    #       export KUBECONFIG=kubeconfig.yaml

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/
        kubectl set image deployment/tourguard-backend tourguard-backend=zafus/tourguard-backend:latest

    #   - name: Verify deployment
    #     run: |
    #       kubectl rollout status deployment/tourguard-backend
    #       kubectl get pods
